=== elFilaly001/NetBeansProjects/test/src/java/DTD/newemptyDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cafe (table*)>
<!ELEMENT table ( long , larg , nape )>
<!ATTLIST table type (carre | triangle | cercle) #REQUIRED>
<!ELEMENT long (#PCDATA)>
<!ELEMENT larg (#PCDATA)>
<!ELEMENT nape (#PCDATA)>

=== elFilaly001/NetBeansProjects/test/src/java/DTD/XML.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE cafe SYSTEM "newemptyDTD.dtd">

<cafe>
    <table type="carre">
        <long> 1.5 </long>
        <larg> 1.5</larg>
        <nape> non </nape>
    </table>
    <table type="carre">
        <long> 2 </long>
        <larg> 2</larg>
        <nape> oui </nape>
    </table>
</cafe>
